# Basic ModSecurity settings
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

# Load CRS setup
Include /etc/modsecurity.d/crs-setup.conf

# Load all CRS rules
Include /etc/modsecurity.d/rules/*.conf

# Disable ModSecurity for Nextcloud WebSocket endpoint
SecRule REQUEST_URI "@beginsWith /push/ws" \
    "id:10001,phase:1,nolog,allow,ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /remote.php/dav" \
    "id:10002,phase:1,nolog,allow,ctl:ruleEngine=Off"

# SecRuleEngine On

# # Audit logging
# SecAuditEngine RelevantOnly
# SecAuditLog /var/log/modsecurity/audit.log
# SecAuditLogFormat JSON

# # Logging parts
# SecAuditLogParts ABIJDEFHZ

# # Basic settings
# SecResponseBodyAccess On
# SecRequestBodyAccess On
# SecRequestBodyLimit 13107200
# SecRequestBodyNoFilesLimit 131072
# SecPcreMatchLimit 100000
# SecPcreMatchLimitRecursion 100000

# # Default actions for rules
# # SecDefaultAction "phase:1,log,deny,status:403"
# # SecDefaultAction "phase:2,log,deny,status:403"

# # Include OWASP CRS
# # Include /etc/modsecurity.d/rules/*.conf

# Include /etc/modsecurity.d/crs-setup.conf
# Include /etc/modsecurity.d/rules/*.conf
