services:

  init-config:
    build:
      context: .
      dockerfile: Dockerfile.init
    volumes:
      - filebrowser_config:/config
    restart: "no"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    depends_on:
      init-config:
        condition: service_completed_successfully
    volumes:
      - filebrowser_config:/config
      - /Users/piusyu/Public/Statements:/srv/Statements
      - /Users/piusyu/Public/Documents certificates:/srv/Documents-Certificates
      - filebrowser_database:/database
    networks:
      - homelab-net
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"

volumes:
  filebrowser_config:
  filebrowser_database:

networks:
  homelab-net:
    external: true
