services:

  init-config:
    image: busybox
    volumes:
      - filebrowser_config:/config
      - ./config/settings.json:/source/settings.json:ro
    command: cp -n /source/settings.json /config/settings.json
    # The init-config service will run once to copy the default settings.json to the calibre_config volume if it doesn't already exist.
    # -n (no-clobber) ensures you don't overwrite existing user data on restarts

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    depends_on:
      init-config:
        condition: service_completed_successfully
    volumes:
      - filebrowser_config:/config
      - /Users/piusyu/Public/Statements:/srv/Statements
      - /Users/piusyu/Public/Documents certificates:/srv/Documents-Certificates
      - filebrowser_database:/database
    networks:
      - homelab-net
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"

volumes:
  filebrowser_config:
  filebrowser_database:

networks:
  homelab-net:
    external: true
