services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data:/var/lib/grafana
    networks:
      - tsdproxy-net
    labels:
      tsdproxy.enable: "true"

volumes:
  grafana-data:

networks:
  tsdproxy-net:
    external: true
