services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    expose:
      - "8080"
    ports:
      - "8081:8080"
    volumes:
      - ${DATA_ROOT}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${DATA_ROOT}/StirlingPDF/extraConfigs:/configs
      - ${DATA_ROOT}/StirlingPDF/customFiles:/customFiles/
      - ${DATA_ROOT}/StirlingPDF/logs:/logs/
      - ${DATA_ROOT}/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    restart: unless-stopped
    networks:
      - homelab-net
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: "8080"
      homepage.group: "Utilities"
      homepage.name: "Stirling PDF"
      homepage.icon: "stirling-pdf"
      homepage.href: "https://stirling-pdf.mulley-bonito.ts.net"
      homepage.description: "A web-based PDF editor that allows you to manage your PDF files through a user-friendly interface. It provides features such as PDF editing, converting, and sharing, making it easy to organize and access your PDF files from anywhere."


networks:
  homelab-net:
    external: true
