services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    # expose:
    #   - "8080"
    # ports:
    #   - "8081:8080"
    volumes:
      - ${DATA_ROOT}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${DATA_ROOT}/StirlingPDF/extraConfigs:/configs
      - ${DATA_ROOT}/StirlingPDF/customFiles:/customFiles/
      - ${DATA_ROOT}/StirlingPDF/logs:/logs/
      - ${DATA_ROOT}/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    restart: unless-stopped
    networks:
      - homelab-net
    labels:
      tsdproxy.enable: "true"

networks:
  homelab-net:
    external: true
