services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab-net
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: "9000"

volumes:
  portainer_data:
    driver: local

networks:
  homelab-net:
    external: true
