services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - ${CONFIG_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  homelab-net:
    external: true
