services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${CONFIG_ROOT}/nginx/conf.d:/etc/nginx/conf.d
      - ${DATA_ROOT}/certbot/conf:/etc/letsencrypt
      - ${DATA_ROOT}/certbot/www:/var/www/certbot
      - ${HOMELAB_ROOT}/docker/reverse-proxy/html:/var/www/home:ro
    networks:
      - homelab-net
    # depends_on:
    #   - jellyfin
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ${DATA_ROOT}/certbot/conf:/etc/letsencrypt
      - ${DATA_ROOT}/certbot/www:/var/www/certbot
    networks:
      - homelab-net
    restart: unless-stopped

  nginx-init:
    image: nginx:latest
    container_name: nginx-init
    volumes:
      - ${CONFIG_ROOT}/nginx/conf.d/certbot-init.conf:/etc/nginx/conf.d/default.conf:ro
      - ${DATA_ROOT}/certbot/www:/var/www/certbot
    networks:
      - homelab-net
    ports:
      - "80:80"
    profiles:
      - init

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    environment:
      - DOMAINS=${DOMAINS}
      - EMAIL=${EMAIL}
    # entrypoint: "/bin/sh -c 'certbot certonly --standalone $DOMAINS --agree-tos -m $EMAIL --no-eff-email && touch /etc/letsencrypt/.certbot-done'"
    entrypoint: "/bin/sh -c 'certbot certonly --webroot -w /var/www/certbot $DOMAINS --agree-tos -m $EMAIL --no-eff-email && touch /etc/letsencrypt/.certbot-done'"
    volumes:
      - ${DATA_ROOT}/certbot/conf:/etc/letsencrypt
      - ${DATA_ROOT}/certbot/www:/var/www/certbot
      - ${DATA_ROOT}/certbot/logs:/var/log/letsencrypt
    networks:
      - homelab-net
    ports:
      - "80:80"
      - "443:443"
    restart: "no"
    profiles:
      - init

networks:
  homelab-net:
    external: true
