services:
  tailscale-cwa:
    image: tailscale/tailscale:latest
    container_name: ts-cwa
    hostname: calibre
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      # - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/calibre-web-automated.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-cwa:/var/lib/tailscale
      - ${CONFIG_ROOT}/tailscale/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=501
      - PGID=20
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # - TZ=UTC 
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - ${DATA_ROOT}/calibre-web-automated:/config 
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - "${MEDIA_ROOT}/Calibre Web Automated/cwa-book-ingest:/cwa-book-ingest"
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - "${MEDIA_ROOT}/Calibre Web Automated/calibre-library:/calibre-library"
    depends_on:
      - tailscale-cwa
    network_mode: service:tailscale-cwa
    # networks:
    #   - homelab-net
    # ports:
    #   - 8083:8083 
    restart: unless-stopped

volumes:
  ts-cwa:
    driver: local

# networks:
#   homelab-net:
#     external: true
