services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus:ro
      - prometheus-data:/prometheus
    networks:
      - tsdproxy-net
    labels:
      tsdproxy.enable: "true"

volumes:
  prometheus-data:

networks:
  tsdproxy-net:
    external: true
