services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped
    networks:
      - homelab-net
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_NUM_THREAD=2

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # ports:
    #   - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - homelab-net
    labels:
      tsdproxy.enable: "true"

volumes:
  ollama_storage:
  open-webui:

networks:
  homelab-net:
    external: true
