services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    container_name: tsdproxy
    env_file:
      - .env.common
    # environment:
      # - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ${SECRETS_ROOT}/tsdproxy-config:/config
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - homelab-net
    
volumes:
  datadir:

networks:
  homelab-net:
    external: true