secrets:
  ts_authkey:
    environment: TSDPROXY_AUTHKEY

services:
  tsdproxy:
    secrets:
      - ts_authkey
    image: almeidapaulopt/tsdproxy:1
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - tsdproxy-net
    
volumes:
  datadir:

networks:
  tsdproxy-net:
    name: tsdproxy-net