services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    env_file:
      - .env.common
    environment:
      - PUID=501
      - PGID=20
    volumes:
      - ${DATA_ROOT}/jellyfin/config:/config
      - ${DATA_ROOT}/jellyfin/cache:/cache
      - ${MEDIA_ROOT}:/media
    networks:
      - homelab-net
    restart: unless-stopped
    # expose:
    #   - "8096"  # Jellyfin's default HTTP port
    # ports:
    #   - "8096:8096"  # for localhost access
    labels:
      tsdproxy.enable: "true"
      homepage.group: "Media"
      homepage.name: "Jellyfin"
      homepage.icon: "jellyfin"
      homepage.href: "https://jellyfin.mulley-bonito.ts.net"
      homepage.description: "Jellyfin is a free and open-source media server that allows you to manage and stream your media files."


networks:
  homelab-net:
    external: true
