services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    # ports:
    #   - 13378:80
    volumes:
      - ${MEDIA_ROOT}/audiobookshelf/audiobooks:/audiobooks
      - ${MEDIA_ROOT}/audiobookshelf/podcasts:/podcasts
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
    environment:
      - TZ=America/Toronto
    networks:
      - homelab-net
    labels:
      tsdproxy.enable: "true"

volumes:
  audiobookshelf-config:
    driver: local
  audiobookshelf-metadata:
    driver: local

networks:
  homelab-net:
    external: true
